<?php
// /public_html/api/game_scorecard/exportScoreCardsPdf.php
declare(strict_types=1);

require_once __DIR__ . '/../../bootstrap.php';
require_once __DIR__ . '/../../vendor/autoload.php'; // composer: tecnickcom/tcpdf
require_once MA_API_LIB . '/Logger.php';
require_once MA_SERVICES . '/context/service_ContextUser.php';
require_once MA_SERVICES . '/context/service_ContextGame.php';
require_once MA_API . '/game_scorecard/initScoreCard.php';

// ==========================================================================
// TCPDF font assets (generated by tc-lib-pdf-font's `make fonts` step).
// Scoped to this file, not bootstrap.php, so a missing/unreadable font
// folder only breaks this one export feature -- not every page on the site.
// ==========================================================================
define('MA_PDF_FONTS', MA_VENDOR . '/tecnickcom/tc-lib-pdf-font/target/fonts/');

if (!is_dir(MA_PDF_FONTS) || !is_readable(MA_PDF_FONTS)) {
    Logger::error('SCORECARD_PDF_FONTS_MISSING', ['path' => MA_PDF_FONTS]);
    http_response_code(500);
    header('Content-Type: application/json; charset=utf-8');
    echo json_encode(['ok' => false, 'error' => 'pdf_fonts_unavailable']);
    exit;
}

if (!defined('K_PATH_FONTS')) {
    define('K_PATH_FONTS', MA_PDF_FONTS);
}

// ==========================================================================
// WHY THIS EXISTS
//
// The on-screen scorecard (game_scorecards.js) renders HTML/CSS and relies
// on window.print() + browser print-dialog settings for page size/orientation.
// That's unreliable across browsers/OSes. Rather than translating that HTML
// through an HTML->PDF converter (still CSS-dependent), this endpoint draws
// the scorecard directly with TCPDF -- same philosophy as
// exportPointScorecards.php using PhpSpreadsheet: explicit layout in code,
// nothing left to a rendering engine's CSS interpretation.
//
// Screen rendering in game_scorecards.js is NOT touched by this file.
// ==========================================================================

// ==========================================================================
// Layout constants (Letter, landscape, points)
// ==========================================================================
const PDF_PAGE_W       = 792.0;  // 11in
const PDF_PAGE_H       = 612.0;  // 8.5in
const PDF_MARGIN       = 14.4;  // 0.2in -- reduced from 24pt/0.33in; still clears the non-printable edge on most printers
const PDF_LABEL_W      = 130.0;  // "HOLE" / player-name column width
const PDF_META_W       = 28.0;   // Out / In / Tot column width (3 of these -- see fix note below)
const PDF_HEADER_ROW_H = 14.0;
const PDF_COURSE_ROW_H = 12.0;
const PDF_PLAYER_ROW_H = 22.0;
const PDF_LOGO_SIZE    = 26.0;
const PDF_QR_SIZE      = 48.0;

// FIX: the previous version divided (w - label - 2*META) by 18, but there
// are THREE meta columns (Out, In, Tot), not two -- that shortfall is why
// the "Tot" column was running past the page edge. Now correctly uses 3x.

// ==========================================================================
// Request handling
// ==========================================================================
header('Content-Type: application/json; charset=utf-8'); // overwritten on success

try {
    $ggid   = (string)($_GET['ggid'] ?? ($_SESSION['SessionStoredGGID'] ?? ''));
    $layout = (string)($_GET['layout'] ?? '2up'); // '1up' | '2up'
    $layout = in_array($layout, ['1up', '2up'], true) ? $layout : '2up';

    // Reuse the exact same data path the screen already trusts -- do NOT
    // accept posted/client HTML. This keeps the PDF endpoint pulling from
    // the same authoritative payload as initScoreCard.php's JSON response,
    // and avoids any question of trusting client-supplied markup.
    $init = initBlankScoreCard($ggid, []);
    if (empty($init['ok'])) {
        http_response_code(404);
        echo json_encode(['ok' => false, 'error' => $init['error'] ?? 'init_failed']);
        exit;
    }

    $game       = $init['game'];
    $scorecards = $init['scorecards'] ?? [];
    $rows       = is_array($scorecards['rows'] ?? null) ? $scorecards['rows'] : [];

    if (!$rows) {
        http_response_code(422);
        echo json_encode(['ok' => false, 'error' => 'no_scorecard_rows']);
        exit;
    }

    $pdf = maBuildScoreCardsPdf($game, $rows, $layout);

    $ggidLabel = (string)($game['dbGames_GGID'] ?? $game['dbGames_GGIDnum'] ?? 'game');
    $filename  = "MatchAid_ScoreCards_{$ggidLabel}_{$layout}.pdf";

    header('Content-Type: application/pdf');
    header('Content-Disposition: inline; filename="' . $filename . '"');
    header('X-MA-ScoreCard-Layout: ' . $layout);
    echo $pdf->Output($filename, 'S');

} catch (Throwable $e) {
    Logger::error('SCORECARD_PDF_EXPORT_FAIL', [
        'err'   => $e->getMessage(),
        'trace' => $e->getTraceAsString(),
    ]);
    http_response_code(500);
    header('Content-Type: application/json; charset=utf-8');
    echo json_encode(['ok' => false, 'error' => 'server_error']);
}

// ==========================================================================
// Font helper -- centralizes the font family so swapping in Montserrat
// later (once its font assets are generated the same way helvetica's were)
// is a one-line change instead of a find/replace across every SetFont call.
// ==========================================================================
function maSetFont(TCPDF $pdf, string $style, float $size): void {
    static $family = 'helvetica'; // TODO: 'montserrat' once custom font assets exist
    $pdf->SetFont($family, $style, $size);
}

// ==========================================================================
// PDF builder
// ==========================================================================
function maBuildScoreCardsPdf(array $game, array $rows, string $layout): TCPDF {
    $pdf = new TCPDF('L', 'pt', [PDF_PAGE_W, PDF_PAGE_H], true, 'UTF-8', false);
    $pdf->SetCreator('MatchAid');
    $pdf->SetAuthor('MatchAid');
    $pdf->setPrintHeader(false);
    $pdf->setPrintFooter(false);
    $pdf->SetMargins(PDF_MARGIN, PDF_MARGIN, PDF_MARGIN);
    $pdf->SetAutoPageBreak(false);
    $pdf->setCellPaddings(2, 2, 2, 2);

    $groupsPerPage = ($layout === '1up') ? 1 : 2;
    $usableH       = PDF_PAGE_H - (2 * PDF_MARGIN);
    $groupH        = $usableH / $groupsPerPage;

    foreach (array_chunk($rows, $groupsPerPage) as $chunk) {
        $pdf->AddPage();
        foreach ($chunk as $i => $group) {
            $yTop = PDF_MARGIN + ($i * $groupH);
            maDrawScoreCardGroup($pdf, $game, $group, $yTop, $groupH);
            if ($groupsPerPage === 2 && $i === 0) {
                // divider between top/bottom groups
                $pdf->SetLineStyle(['width' => 0.75, 'color' => [180, 180, 180], 'dash' => '2,2']);
                $pdf->Line(PDF_MARGIN, $yTop + $groupH - 4, PDF_PAGE_W - PDF_MARGIN, $yTop + $groupH - 4);
                $pdf->SetLineStyle(['dash' => 0]);
            }
        }
    }

    return $pdf;
}

/**
 * Draws one group (one scorecard) inside the vertical band [$yTop, $yTop+$maxH].
 * Mirrors the section structure of renderGroup()/renderTable()/renderFooter()
 * in game_scorecards.js, translated into direct TCPDF drawing calls.
 */
function maDrawScoreCardGroup(TCPDF $pdf, array $game, array $group, float $yTop, float $maxH): void {
    $gh = $group['gameHeader'] ?? [];
    $x  = PDF_MARGIN;
    $w  = PDF_PAGE_W - (2 * PDF_MARGIN);

    // ---- Header block (logo, title, sublines, QR, live-scoring link) -----
    $y = maDrawHeaderBlock($pdf, $game, $gh, $group, $x, $yTop, $w);
    $y += 4;

    // ---- Table -------------------------------------------------------
    $courseRows  = is_array($group['courseInfo'] ?? null) ? $group['courseInfo'] : [];
    $players     = is_array($group['players'] ?? null) ? $group['players'] : [];
    $isMatchPlay = strtolower((string)($group['competition'] ?? '')) === 'pairpair';

    // FIX: 3 meta columns (Out, In, Tot), not 2 -- see const block above.
    $holeColW = ($w - PDF_LABEL_W - (3 * PDF_META_W)) / 18;

    $pdf->SetXY($x, $y);
    maSetFont($pdf, 'B', 8);
    $pdf->SetFillColor(235, 235, 235);

    // header row: HOLE | 1..9 | Out | 10..18 | In | Tot
    $pdf->Cell(PDF_LABEL_W, PDF_HEADER_ROW_H, 'HOLE', 1, 0, 'C', true);
    for ($h = 1; $h <= 9; $h++) $pdf->Cell($holeColW, PDF_HEADER_ROW_H, (string)$h, 1, 0, 'C', true);
    $pdf->Cell(PDF_META_W, PDF_HEADER_ROW_H, 'Out', 1, 0, 'C', true);
    for ($h = 10; $h <= 18; $h++) $pdf->Cell($holeColW, PDF_HEADER_ROW_H, (string)$h, 1, 0, 'C', true);
    $pdf->Cell(PDF_META_W, PDF_HEADER_ROW_H, 'In', 1, 0, 'C', true);
    $pdf->Cell(PDF_META_W, PDF_HEADER_ROW_H, 'Tot', 1, 1, 'C', true);

    // course info rows (Par, HCP, Yardage, ...)
    foreach ($courseRows as $r) {
        $pdf->SetX($x);
        $label = maBuildCourseRowLabel($r);
        maSetFont($pdf, 'B', 8);
        $pdf->Cell(PDF_LABEL_W, PDF_COURSE_ROW_H, $label, 1, 0, 'L');
        maSetFont($pdf, '', 8);
        for ($h = 1; $h <= 9; $h++) $pdf->Cell($holeColW, PDF_COURSE_ROW_H, (string)($r['h' . $h] ?? ''), 1, 0, 'C');
        maSetFont($pdf, 'B', 8);
        $pdf->Cell(PDF_META_W, PDF_COURSE_ROW_H, (string)($r['9a'] ?? ''), 1, 0, 'C');
        maSetFont($pdf, '', 8);
        for ($h = 10; $h <= 18; $h++) $pdf->Cell($holeColW, PDF_COURSE_ROW_H, (string)($r['h' . $h] ?? ''), 1, 0, 'C');
        maSetFont($pdf, 'B', 8);
        $pdf->Cell(PDF_META_W, PDF_COURSE_ROW_H, (string)($r['9b'] ?? ''), 1, 0, 'C');
        $pdf->Cell(PDF_META_W, PDF_COURSE_ROW_H, (string)($r['9c'] ?? ''), 1, 1, 'C');
    }

    // player rows (blank score boxes with small stroke-mark numerals)
    $slots = $isMatchPlay
        ? [$players[0] ?? null, $players[1] ?? null, null, $players[2] ?? null, $players[3] ?? null, null]
        : array_pad(array_slice($players, 0, 4), 6, null);

    foreach ($slots as $p) {
        $rowY = $pdf->GetY();
        $pdf->SetX($x);

        // Draw the bordered name cell empty first, then overlay two lines
        // of text on top of it (name+HC bold, tee small/gray beneath) --
        // Cell() can't do two lines on its own.
        $pdf->Cell(PDF_LABEL_W, PDF_PLAYER_ROW_H, '', 1, 0, 'L');
        if ($p) {
            $name = (string)($p['playerName'] ?? '');
            $hc   = is_numeric($p['playerHC'] ?? null) ? " ({$p['playerHC']})" : '';
            $tee  = (string)($p['tee'] ?? '');

            $pdf->SetXY($x + 3, $rowY);
            maSetFont($pdf, 'B', 8);
            $pdf->Cell(PDF_LABEL_W - 6, 10, $name . $hc, 0, 0, 'L');

            if ($tee !== '') {
                $pdf->SetXY($x + 3, $rowY + 10);
                maSetFont($pdf, '', 8);
                $pdf->Cell(PDF_LABEL_W - 6, 8, $tee, 0, 0, 'L');
            }
        }

        $cx = $x + PDF_LABEL_W;
        for ($h = 1; $h <= 9; $h++) {
            $pdf->SetXY($cx, $rowY);
            $pdf->Cell($holeColW, PDF_PLAYER_ROW_H, '', 1, 0, 'C');
            if ($p) maDrawStrokeMark($pdf, $cx, $rowY, $holeColW, $p['strokes']['h' . $h] ?? null);
            $cx += $holeColW;
        }
        $pdf->SetXY($cx, $rowY);
        $pdf->Cell(PDF_META_W, PDF_PLAYER_ROW_H, '', 1, 0, 'C');
        $cx += PDF_META_W;
        for ($h = 10; $h <= 18; $h++) {
            $pdf->SetXY($cx, $rowY);
            $pdf->Cell($holeColW, PDF_PLAYER_ROW_H, '', 1, 0, 'C');
            if ($p) maDrawStrokeMark($pdf, $cx, $rowY, $holeColW, $p['strokes']['h' . $h] ?? null);
            $cx += $holeColW;
        }
        $pdf->SetXY($cx, $rowY);
        $pdf->Cell(PDF_META_W, PDF_PLAYER_ROW_H, '', 1, 0, 'C');
        $cx += PDF_META_W;
        $pdf->SetXY($cx, $rowY);
        $pdf->Cell(PDF_META_W, PDF_PLAYER_ROW_H, '', 1, 1, 'C');
        $pdf->SetXY($x, $rowY + PDF_PLAYER_ROW_H);
    }

    // ---- Footer (SCORER / ATTEST lines + Game/Pairings + copyright) ------
    $footerY = $pdf->GetY() + 8;
    maDrawFooter($pdf, $gh, $group, $x, $footerY, $w);
}

/**
 * Header block: logo + title/sublines on the left, "Live Scoring at..."
 * text + a real embedded QR code on the right. Mirrors the 4-line header
 * (title / subLine / line3 / line4) built in renderGroup() on screen.
 * Returns the Y coordinate where the table should start.
 */
function maDrawHeaderBlock(TCPDF $pdf, array $game, array $gh, array $group, float $x, float $y, float $w): float {
    $logoPath = MA_ROOT . '/assets/images/MatchAidLogoSquare.jpeg';
    $textX    = $x;

    if (is_file($logoPath) && is_readable($logoPath)) {
        try {
            $pdf->Image($logoPath, $x, $y, PDF_LOGO_SIZE, PDF_LOGO_SIZE);
            $textX = $x + PDF_LOGO_SIZE + 8;
        } catch (Throwable $e) {
            // A bad/corrupt/unsupported logo file should never take down
            // the whole PDF -- log it and just render without the logo.
            Logger::error('SCORECARD_PDF_LOGO_SKIPPED', ['path' => $logoPath, 'err' => $e->getMessage()]);
        }
    }

    // ---- Live-scoring text + QR geometry, computed up front -------------
    // Measured (not guessed) so the title row knows exactly how much room
    // to leave for the text sitting beside it. Rows 2-4 don't share their
    // row with anything on the right, so they get the full width later.
    $scoreCardId = trim((string)($gh['playerKey'] ?? ''));
    $hasQr = ($scoreCardId !== '' && !empty($gh['GGID']));
    $qrX   = $x + $w - PDF_QR_SIZE;
    $qrY   = $y;

    $linkTx = '';
    $linkX  = $qrX;
    $linkW  = 0.0;
    if ($hasQr) {
        $host   = parse_url(MA_SITE_URL, PHP_URL_HOST) ?: MA_SITE_URL;
        $linkTx = "Live Scoring at {$host}/score/{$scoreCardId}";
        maSetFont($pdf, '', 8);
        $linkW  = $pdf->GetStringWidth($linkTx) + 6;
        $linkX  = $qrX - 8 - $linkW;
    }

    $titleW = ($hasQr ? $linkX : $x + $w) - 8 - $textX; // shares the row with the live-scoring text
    $fullW  = $qrX - 8 - $textX;                        // rows below have the whole row to themselves

    // Tight padding for just these 4 header lines (this is the actual
    // source of the gap under the QR code) -- restored to normal right
    // after line 4, before the grid or anything else draws.
    $pdf->setCellPaddings(1, 0.5, 1, 0.5);

    // Title
    $pdf->SetXY($textX, $y);
    maSetFont($pdf, 'B', 13);
    $pdf->Cell($titleW, 14, (string)($gh['gameTitle'] ?? 'Game'), 0, 1, 'L');

    // Sub-line: course • date • tee time • start hole -- stretches to the QR
    $pdf->SetX($textX);
    maSetFont($pdf, '', 9);
    $pdf->Cell($fullW, 10, maBuildSubLine($game, $gh, $group), 0, 1, 'L');

    // Line 3: format / HC effectivity / allowance / stroke distribution
    $line3 = maBuildLine3($game, $gh);
    if ($line3 !== '') {
        $pdf->SetX($textX);
        maSetFont($pdf, 'B', 8);
        $pdf->Cell($fullW, 9, $line3, 0, 1, 'L');
    }

    // Line 4: scoring system
    $line4 = maBuildLine4($game);
    if ($line4 !== '') {
        $pdf->SetX($textX);
        maSetFont($pdf, '', 8);
        $pdf->Cell($fullW, 9, $line4, 0, 1, 'L');
    }

    $pdf->setCellPaddings(2, 2, 2, 2); // restore normal padding for everything after the header

    $leftBottom = $pdf->GetY();

    // ---- Right side: live-scoring link (top-aligned, left of QR) + QR ----
    if ($hasQr) {
        $pdf->SetXY($linkX, $y + 2); // nudged to optically align with the title's cap-height, not its full line box
        maSetFont($pdf, '', 8);
        $pdf->Cell($linkW, 12, $linkTx, 0, 0, 'L');

        $qrUrl = rtrim(MA_SITE_URL, '/') . '/score/' . rawurlencode($scoreCardId);
        $qrStyle = [
            'border'   => false,
            'vpadding' => 0,
            'hpadding' => 0,
            'fgcolor'  => [0, 0, 0],
            'bgcolor'  => false,
        ];
        $pdf->write2DBarcode($qrUrl, 'QRCODE,M', $qrX, $qrY, PDF_QR_SIZE, PDF_QR_SIZE, $qrStyle, 'N');
    }

    $rightBottom = $qrY + PDF_QR_SIZE;

    return max($leftBottom, $rightBottom, $y + PDF_LOGO_SIZE);
}

/** Small superscript-style numeral in the top-right corner of a score cell (blue, matches on-screen stroke marks). */
function maDrawStrokeMark(TCPDF $pdf, float $cellX, float $cellY, float $cellW, $n): void {
    $num = is_numeric($n) ? (float)$n : 0.0;
    if ($num === 0.0) return;
    $text = ($num < 0 ? '-' : '') . abs((int)$num);
    maSetFont($pdf, '', 6);
    $pdf->SetTextColor(30, 70, 160);
    $pdf->SetXY($cellX + $cellW - 10, $cellY + 1);
    $pdf->Cell(9, 8, $text, 0, 0, 'R');
    $pdf->SetTextColor(0, 0, 0);
}

/**
 * Course-info row label. FIX: previously dropped the tee-name suffix
 * entirely (e.g. showed bare "2" instead of "2 — Yards") -- mirrors the
 * JS: append " — {tee}" unless the row is Par or HCP.
 */
function maBuildCourseRowLabel(array $r): string {
    $label = (string)($r['label'] ?? '');
    $tee   = (string)($r['tee'] ?? '');
    if ($tee !== '' && !in_array($label, ['Par', 'HCP'], true)) {
        $label .= ' — ' . $tee;
    }
    return $label;
}

/** Mirrors the subLine construction in renderGroup() (course • date • tee time • start hole). */
function maBuildSubLine(array $game, array $gh, array $group): string {
    $parts = [];
    if (!empty($gh['courseName'])) $parts[] = (string)$gh['courseName'];
    if (!empty($gh['playDate']))   $parts[] = maFormatPdfDate((string)$gh['playDate']);
    if (!empty($group['teeTime'])) $parts[] = (string)$group['teeTime'];

    $suffix = $group['startHoleSuffix'] ?? '';
    if (!$suffix && !empty($group['players']) && is_array($group['players'])) {
        foreach ($group['players'] as $pl) {
            if (!empty($pl['dbPlayers_StartHoleSuffix'] ?? $pl['startHoleSuffix'] ?? '')) {
                $suffix = $pl['dbPlayers_StartHoleSuffix'] ?? $pl['startHoleSuffix'];
                break;
            }
        }
    }
    if (!empty($group['startHole'])) {
        $parts[] = "Start: Hole {$group['startHole']}{$suffix}";
    }
    return implode('  •  ', $parts);
}

/** Mirrors line3 in renderGroup(): Format / HC effectivity / Allowance / Stroke Distribution / Segments. */
function maBuildLine3(array $game, array $gh): string {
    $gameFormat   = trim((string)($gh['dbGames_GameFormat'] ?? $game['dbGames_GameFormat'] ?? ''));
    $scoringBasis = trim((string)($game['dbGames_ScoringBasis'] ?? ''));
    $scoringMethod = trim((string)($game['dbGames_ScoringMethod'] ?? ''));
    $strokeDist   = trim((string)($game['dbGames_StrokeDistribution'] ?? ''));
    $allowanceRaw = trim((string)($game['dbGames_Allowance'] ?? ''));
    $hcEff        = trim((string)($game['dbGames_HCEffectivity'] ?? ''));
    $hcDate       = trim((string)($game['dbGames_HCEffectivityDate'] ?? ''));

    $formatLabel = '';
    if ($gameFormat && $scoringBasis && $scoringMethod) {
        $formatLabel = "Format: {$gameFormat} based on {$scoringBasis} using {$scoringMethod} scoring";
    } elseif ($gameFormat && $scoringBasis) {
        $formatLabel = "Format: {$gameFormat} based on {$scoringBasis}";
    } elseif ($gameFormat && $scoringMethod) {
        $formatLabel = "Format: {$gameFormat} using {$scoringMethod} scoring";
    } elseif ($gameFormat) {
        $formatLabel = "Format: {$gameFormat}";
    }

    $isGrossScoring = in_array(strtoupper($scoringMethod), ['GROSS', 'ADJ GROSS'], true);

    $hcLabel = '';
    if (!$isGrossScoring) {
        if ($hcEff === 'Date' && $hcDate) {
            $hcLabel = "HC Effective as of {$hcDate}";
        } elseif ($hcEff) {
            $hcLabel = "HCP Effective using {$hcEff}";
        }
    }

    $allowanceLabel = (!$isGrossScoring && $allowanceRaw) ? "Allowance {$allowanceRaw}%" : '';
    $strokeDistLabel = $strokeDist ? "Stroke Distribution {$strokeDist}" : '';

    $segmentLabel = '';
    $rotation = trim((string)($gh['dbGames_RotationMethod'] ?? $game['dbGames_RotationMethod'] ?? ''));
    if ($rotation !== 'None') {
        $seg = trim((string)($gh['dbGames_Segments'] ?? $game['dbGames_Segments'] ?? ''));
        if ($seg !== '') $segmentLabel = "{$seg}-Hole Segments";
    }

    return implode('  •  ', array_filter([$formatLabel, $hcLabel, $allowanceLabel, $strokeDistLabel, $segmentLabel], fn($v) => $v !== ''));
}

/** Mirrors line4 in renderGroup(): Scoring System (BestBall / DeclareHole / DeclarePlayer / DeclareManual / AllScores / other). */
function maBuildLine4(array $game): string {
    $sys = trim((string)($game['dbGames_ScoringSystem'] ?? ''));
    if ($sys === '') return '';

    if ($sys === 'BestBall') {
        $cnt = trim((string)($game['dbGames_BestBallCnt'] ?? $game['dbGames_BestBall'] ?? ''));
        return $cnt ? "Scoring System: Best {$cnt} Ball" . ($cnt === '1' ? '' : 's') : 'Scoring System: Best Ball';
    }

    if ($sys === 'DeclareHole') {
        $raw = $game['dbGames_HoleDeclaration'] ?? '';
        $map = [];
        $parsed = is_string($raw) ? json_decode($raw, true) : $raw;
        if (is_array($parsed)) {
            if (array_is_list($parsed)) {
                foreach ($parsed as $r) {
                    if (isset($r['hole'])) $map[(string)$r['hole']] = $r['count'] ?? null;
                }
            } else {
                $map = $parsed;
            }
        }
        $pairs = [];
        for ($h = 1; $h <= 18; $h++) {
            $val = $map[(string)$h] ?? $map[$h] ?? null;
            if ($val !== null && $val !== '') $pairs[] = "H{$h}:{$val}";
        }
        return $pairs ? 'Scoring System: Declare by Hole (' . implode('  •  ', $pairs) . ')' : 'Scoring System: Declare by Hole';
    }

    if ($sys === 'DeclarePlayer') {
        $perPlayer = trim((string)($game['dbGames_PlayerDeclaration'] ?? '1'));
        return "Scoring System: Declare by Player ({$perPlayer}x per player)";
    }

    if ($sys === 'DeclareManual') return 'Scoring System: Declare Scores Discretionally';
    if ($sys === 'AllScores')     return 'Scoring System: Use All Scores';

    return "Scoring System: {$sys}";
}

/** Mirrors renderFooter(): SCORER/ATTEST lines + Game/Match/Pairings left, copyright right. */
function maDrawFooter(TCPDF $pdf, array $gh, array $group, float $x, float $y, float $w): void {
    $isPairPair = trim((string)($gh['dbGames_Competition'] ?? '')) === 'PairPair';
    $pairingIDs = array_filter(is_array($group['pairingIDs'] ?? null) ? $group['pairingIDs'] : (array)($group['pairingID'] ?? []));
    $flightIDs  = array_filter(is_array($group['flightIDs'] ?? null) ? $group['flightIDs'] : (array)($group['flightID'] ?? []));

    $leftParts = [];
    if (!empty($gh['GGID'])) $leftParts[] = "Game {$gh['GGID']}";
    if ($isPairPair && $flightIDs) $leftParts[] = 'Match ' . implode(', ', $flightIDs);
    if ($pairingIDs) $leftParts[] = 'Pairings ' . implode(', ', $pairingIDs);
    $leftText = implode('  •  ', $leftParts);
    $copyText = '© ' . date('Y') . ' MatchAid';

    maSetFont($pdf, '', 7);
    $leftW = $leftText !== '' ? $pdf->GetStringWidth($leftText) + 6 : 0.0;
    $copyW = $pdf->GetStringWidth($copyText) + 6;

    // Game/Match/Pairings -- far left, small/gray
    if ($leftText !== '') {
        $pdf->SetTextColor(120, 120, 120);
        $pdf->SetXY($x, $y);
        $pdf->Cell($leftW, 10, $leftText, 0, 0, 'L');
        $pdf->SetTextColor(0, 0, 0);
    }

    // SCORER / ATTEST -- split the remaining middle space evenly
    $gap = 16.0;
    $middleW = $w - $leftW - $copyW - (2 * $gap);
    $halfW   = $middleW / 2;

    $scorerX = $x + $leftW + $gap;
    $pdf->SetXY($scorerX, $y);
    $pdf->Cell($halfW, 10, 'SCORER  _____________________', 0, 0, 'L');

    $attestX = $scorerX + $halfW;
    $pdf->SetXY($attestX, $y);
    $pdf->Cell($halfW, 10, 'ATTEST  _____________________', 0, 0, 'L');

    // Copyright -- far right
    $pdf->SetXY($x + $w - $copyW, $y);
    $pdf->Cell($copyW, 10, $copyText, 0, 1, 'R');
}

function maFormatPdfDate(string $s): string {
    $d = DateTime::createFromFormat('Y-m-d', $s) ?: (new DateTime($s));
    return $d ? $d->format('D m/d/y') : $s;
}
